name: auto_Reserve

on:
  schedule:
    # 北京时间 19:00 运行 (UTC+8)
    - cron: "30 12 * * *"   # 保持 UTC 时间 11:00（对应北京时间 19:00）
      timezone: "Asia/Shanghai"  # 显式声明时区
  workflow_dispatch:  # 保留手动触发功能

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          
      - name: install dependency
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install build-essential libssl-dev libffi-dev python3-dev -y
          pip install cryptography requests opencv-python numpy pytz

      - name: run script
        env:
          USERNAMES: ${{ secrets.USERNAMES }}
          PASSWORDS: ${{ secrets.PASSWORDS }}
        run: |
          python main.py -m debug --action
